spring:
  main:
    web-application-type: none
    banner-mode: off
    lazy-initialization: true

logging.level:
  root: warn
  ru.itmo: info
  edu.stanford.nlp.process.PTBLexer: error

stand:
  app:
    base-path: "."
    neighbours-algorithm:
      window-size: 5
      bert-model-type: BASE
      bert-window-batch-size: 1000
      documents-count: 500000
      embedding-storage: IN_MEMORY
    bert-multi-token:
      token-batch-size: 5
