spring:
  main:
    web-application-type: none
    banner-mode: off
    lazy-initialization: true
  data.mongodb:
    database: ir-stand
    auto-index-creation: true

logging.level:
  root: warn
  ru.itmo: info
  edu.stanford.nlp.process.PTBLexer: error

stand:
  elasticsearch.host-and-port: localhost:9200
  app:
    base-path: "."
    file-load-buffer-size-mb: 512
    neighbours-algorithm:
      token-batch-size: 5
      bert-model-type: TINY
      documents-count: 500000
    bert-multi-token:
      token-batch-size: 5
