spring:
  main:
    web-application-type: none
    banner-mode: off
    lazy-initialization: true
  data.mongodb:
    database: document
    auto-index-creation: true

logging.level:
  root: error
  ru.itmo: info

stand:
  elasticsearch.host-and-port: localhost:9200
  app:
    base-path: "."

    bert-multi-token:
      token-batch-size: 5
